### ISSUE TITLE
データベースの構築

### ISSUE THREAD

**Issue by hidaiori** [T1-2022/yoyaku#4]
- [x] データベース設計について調査
- [x] データベース設計の話し合い
- [x] データベースの追加項目
- [x] 成果物の確認作業

**Comment by onherrerap** [comment]
https://support.microsoft.com/ja-jp/office/%E3%83%87%E3%83%BC%E3%82%BF%E3%83%99%E3%83%BC%E3%82%B9%E8%A8%AD%E8%A8%88%E3%81%AE%E5%9F%BA%E6%9C%AC-eb2159cf-1e30-401a-8084-bd4f9c9ca1f5
